<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Metering extends Model
{
    use HasFactory;

    protected $table = 'metering';
    protected $primaryKey = 'id_metering';
    protected $fillable = [
        'project',
        'section',
        'device',
        'sn',
        'status',
        'Freq_Hz',
        'V1',
        'V2',
        'V3',
        'Vnavg_V',
        'V12',
        'V23',
        'V31',
        'VIavg_V',
        'I1',
        'I2',
        'I3',
        'Iavg_A',
        'P1',
        'P2',
        'P3',
        'Psum_kW',
        'Q1',
        'Q2',
        'Q3',
        'Qsum_kvar',
        'S1',
        'S2',
        'S3',
        'Ssum_kVA',
        'PF1',
        'PF2',
        'PF3',
        'PF',
        'Unbl_V',
        'Unbl_I',
        'LCavg',
        'DMD_P_kW',
        'DMD_Q_kvar',
        'DMD_S_kVA',
        'EP_IMP_kWh',
        'EP_EXP_kWh',
        'EQ_IMP_kvarh',
        'EQ_EXP_kvarh',
        'EP_TOTAL_kWh',
        'EP_NET_kWh',
        'EQ_TOTAL_kvarh',
        'EQ_NET_kvarh',
        'ES_kVAh',
        'THD_Va',
        'THD_Vb',
        'THD_Vc',
        'THD_Vavg',
        'THD_Ia',
        'THD_Ib',
        'THD_Ic',
        'THD_Iavg',
        'Ang_Vb',
        'Ang_Vc',
        'Ang_Ia',
        'Ang_Ib',
        'Ang_Ic',
        'DMD_I1_A',
        'DMD_I2_A',
        'DMD_I3_A',
        'EPa_IMP_kWh',
        'EPa_EXP_kWh',
        'EPb_IMP_kWh',
        'EPb_EXP_kWh',
        'EPc_IMP_kWh',
        'EPc_EXP_kWh',
        'EQa_IMP_kvarh',
        'EQa_EXP_kvarh',
        'EQb_IMP_kvarh',
        'EQb_EXP_kvarh',
        'EQc_IMP_kvarh',
        'EQc_EXP_kvarh',
        'ESa_kVAh',
        'ESb_kVAh',
        'ESc_kVAh',      
    ];
    public $timestamps = true;
}
